# Authentifications
login:
    path:   /login
    defaults:  { _controller: UserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   /logout

# Controllers annotations
controllers:
    resource: "@UserBundle/Controller/"
    type:     annotation