app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# Import the routing file of the UserBundle
user:
    resource: "@UserBundle/Resources/config/routing.yml"

api:
    resource: "@ApiBundle/Controller/"
    type:     annotation
    prefix:   api/

