# Main Application routes are defined in all controller as annotations
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# User / authentification at backend routes are defined in the routing file of the UserBundle
user:
    resource: "@UserBundle/Resources/config/routing.yml"

# api routes are defined in the routing file of the ApiBundle
api:
    resource: "@ApiBundle/Resources/config/routing.yml"





# RSS Atom Bundle
rssatom:
    resource: "@DebrilRssAtomBundle/Resources/config/routing.yml"