# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
        # This one is used e.g when we generate a password from the "bin/console security:encode-password" command. For system stuff
        Symfony\Component\Security\Core\User\User:
            algorithm: sha512
            encode_as_base64: false # Don't encode in base64 because if I used Fixtures to load data, I create password with php function : hash('512', raw)
            iterations: 1
        # This one is used when we log in
        App\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false # Don't encode in base64 because if I used Fixtures to load data, I create password with php function : hash('512', raw,)
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:   ROLE_WRITER

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
            entity:
                class:    UserBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:   ^/
            anonymous: true
            provider:  main
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path:   logout
                target: /login
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }